[package]
name = "starknet"
version = "0.1.0"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
license = "MIT"
edition = "2021"
readme = "README.md"
documentation = "https://docs.rs/starknet"
repository = "https://github.com/xJonathanLEI/starknet-rs"
homepage = "https://starknet.rs/"
description = """
Complete StarkNet library in Rust
"""

[workspace]
members = [
    "starknet-core",
    "starknet-providers",
]

[dependencies]
starknet-core = { version = "0.1.0", path = "./starknet-core" }
starknet-providers = { version = "0.1.0", path = "./starknet-providers" }
