[package]
name = "starknet-core"
version = "0.1.0"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/xJonathanLEI/starknet-rs"
homepage = "https://starknet.rs/"
description = """
Core structures for the starknet crate
"""

[dependencies]
ethereum-types = "0.12.1"
hex = "0.4.3"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
